# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShEnxcRw2H2blja_AD4VamJhVlvnS6lr

**Install and import required Libraries**
"""

!pip install surprise
!pip install "numpy<2.0"

# Basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Load Data sets**"""

# load listings data
listings_df = pd.read_csv('listings (1).csv.gz', compression='gzip')
listings_df.head()

listings_df.info()

# load reviews data
reviews_df = pd.read_csv('reviews.csv.gz', compression='gzip')
reviews_df.head()

reviews_df.info()

"""**Data Pre-Processing**"""

reviews_df.isna().sum()

reviews_df.dropna(inplace=True)

reviews_df.info()

"""Merge both data set into a single DataFrame using a common identifier, where the id column from the listing’s dataset was matched with the listing_id column from the review’s dataset"""

dublin_merged_df = pd.merge(listings_df, reviews_df, left_on='id', right_on='listing_id')
dublin_merged_df.head(1)

dublin_merged_df.duplicated().sum()

dublin_merged_df.isna().sum()

dublin_merged_df['neighbourhood_cleansed'].nunique()

dublin_merged_df['neighbourhood'].nunique()

dublin_merged_df['property_type'].nunique()

dublin_merged_df['room_type'].nunique()

columns_to_drop = [
    'scrape_id', 'last_scraped', 'name',
    'neighborhood_overview', 'host_url',
    'host_name', 'host_location', 'host_about', 'host_thumbnail_url',
    'host_picture_url', 'host_neighbourhood', 'host_verifications',
    'neighbourhood_group_cleansed', 'host_total_listings_count', 'property_type',
    'minimum_minimum_nights', 'maximum_minimum_nights', 'bathrooms_text', 'minimum_maximum_nights',
    'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm',
    'calendar_updated', 'neighbourhood', 'calendar_last_scraped', 'number_of_reviews_ltm', 'license', 'has_availability',
    'host_id', 'source', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes',
    'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms'
]

# Drop the specified columns
dublin_merged_df = dublin_merged_df.drop(columns=columns_to_drop)

"""Several variables were removed prior to modelling to improve data quality and reduce dimensionality. These included unique identifiers and URLs (e.g., scrape_id, host_id, listing_url), which do not contain predictive information; redundant or higher-level location descriptors (e.g., neighbourhood, neighbourhood_group_cleansed), which duplicate spatial effects already captured by geographic coordinates; and long free-text fields (e.g., host_about, neighborhood_overview), which would require separate natural language processing pipelines. Additionally, technical calendar fields and derived booking constraint variables (e.g., minimum_nights_avg_ntm, calendar_updated) were excluded as they describe data collection processes rather than intrinsic listing characteristics. Finally, calculated host listing count variables were dropped because they replicate information already captured by host_listings_count, leading to multicollinearity without adding independent explanatory value."""

# check remaining columns
dublin_merged_df.columns

# data type check
dublin_merged_df.info()

dublin_merged_df.isna().sum()

"""Remove rows with missing values in our target variable. This is because imputating the target variable would create artificial data, introduce bias and can also lead to data leakage."""

dublin_merged_df.dropna(subset=['price'], inplace=True)

dublin_merged_df.isna().sum()

"""Missing values were treated based on their semantic meaning and distribution. Remove rows with missing values in the target variable. This is because imputating the target variable would
create artificial data, introduce bias and can also lead to data leakage.
Structural listing attributes (bathrooms, bedrooms, and beds) had minimal missingness and were imputed using the median to preserve robustness against skewness. Host-related categorical features with high missingness were imputed with an "Unknown" category to avoid introducing false information. Host response and acceptance rates were converted to numeric format and imputed using the median, alongside missingness indicator variables to retain potential information encoded in missing values. Text fields such as listing descriptions were replaced with empty strings. No rows were removed to avoid systematic bias and loss of information.
"""

# TEXT FIELDS
dublin_merged_df['description'] = dublin_merged_df['description'].fillna("")


# HOST RESPONSE COLUMNS
rate_cols = ['host_response_rate', 'host_acceptance_rate']

for col in rate_cols:
    # Remove % and convert to numeric
    dublin_merged_df[col] = dublin_merged_df[col].str.replace('%', '', regex=False)
    dublin_merged_df[col] = pd.to_numeric(dublin_merged_df[col], errors='coerce')

    # Impute with median
    dublin_merged_df[col] = dublin_merged_df[col].fillna(dublin_merged_df[col].median())


# HOST RESPONSE TIME
dublin_merged_df['host_response_time'] = dublin_merged_df['host_response_time'].fillna("Unknown")

# HOST SUPERHOST STATUS
dublin_merged_df['host_is_superhost'] = dublin_merged_df['host_is_superhost'].fillna("Unknown")

# HOST PROFILE INFO
dublin_merged_df['host_has_profile_pic'] = dublin_merged_df['host_has_profile_pic'].fillna("Unknown")
dublin_merged_df['host_identity_verified'] = dublin_merged_df['host_identity_verified'].fillna("Unknown")

# Convert host_since to datetime and impute
dublin_merged_df['host_since'] = pd.to_datetime(dublin_merged_df['host_since'], errors='coerce')
dublin_merged_df['host_since'] = dublin_merged_df['host_since'].fillna(dublin_merged_df['host_since'].median())

# Host listings count
dublin_merged_df['host_listings_count'] = dublin_merged_df['host_listings_count'].fillna(dublin_merged_df['host_listings_count'].median())

# STRUCTURAL NUMERIC FEATURES
num_cols = ['bathrooms', 'bedrooms', 'beds']

for col in num_cols:
    dublin_merged_df[col] = dublin_merged_df[col].fillna(dublin_merged_df[col].median())

# FINAL CHECK
print(dublin_merged_df.isna().sum().sort_values(ascending=False))

# dublin_merged_df.dropna(inplace=True)

#check null
dublin_merged_df.isna().sum().sum()

# Remove currency symbols and commas from the 'price' column, then convert to float
dublin_merged_df['price'] = dublin_merged_df['price'].replace('[$,]', '', regex=True).astype(float)

"""Convert Date to datetime format for data integrity and enabling accurate analysis."""

# Convert 'date' to datetime format
dublin_merged_df['date'] = pd.to_datetime(dublin_merged_df['date'])

# Convert host_since to datetime
dublin_merged_df['host_since'] = pd.to_datetime(dublin_merged_df['host_since'], errors='coerce')

# Convert host_since to datetime first_review and last_review
dublin_merged_df['first_review'] = pd.to_datetime(dublin_merged_df['first_review'])
dublin_merged_df['last_review'] = pd.to_datetime(dublin_merged_df['last_review'])

print(f"Of the Airbnb hosts that are still listing on the site, the first joined on {min(dublin_merged_df.host_since).strftime('%d %B %Y')}, and the most recent joined on {max(dublin_merged_df.host_since).strftime('%d %B %Y')}.")

numeric_cols = dublin_merged_df.select_dtypes(include=['number']).columns
len(numeric_cols)

categorical_cols = dublin_merged_df.select_dtypes(include=['object']).columns
len(categorical_cols)

import math

# Calculate rows needed for a 4-column wide grid
n_cols = 4
n_rows = math.ceil(len(numeric_cols) / n_cols)

plt.figure(figsize=(16, 4 * n_rows)) # Adjust height based on rows

for i, col in enumerate(numeric_cols):
    ax = plt.subplot(n_rows, n_cols, i + 1)
    sns.boxplot(y=dublin_merged_df[col], color="#5da5da")
    plt.title(col.upper(), fontweight='bold')

plt.tight_layout()
plt.show()

"""Price Distribution"""

# mean of the 'price' column
mean_value = dublin_merged_df['price'].mean()

# histogram
sns.histplot(dublin_merged_df['price'], kde=True)

# Add a vertical line at the mean
plt.axvline(mean_value, color='red', linestyle='dashed', linewidth=1, label=f'Mean: {mean_value:.2f}')

# Add legend and labels
plt.legend()
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Distribution of Price')

plt.show();

from IPython.display import Image, HTML

# 1. Get unique listings, sorted by price (assuming 'price' is the column name)
top_listings = dublin_merged_df.drop_duplicates('listing_id').sort_values(by='price', ascending=False).head(5)

# 2. Function to convert URL to HTML image tag
def path_to_image_html(path):
    return f'<img src="{path}" width="200" >'

# 3. Select columns and display with rendered images
# Update 'price' if your column is named differently (e.g., 'price_x')
display_cols = ['price', 'picture_url', 'listing_url', 'description']
output = top_listings[display_cols]

# Render the table with images
HTML(output.to_html(escape=False, formatters=dict(picture_url=path_to_image_html)))

dublin_merged_df['price'].describe()

plt.figure(figsize=(8, 4))
plt.boxplot(dublin_merged_df['price'], vert=False)
plt.title('Boxplot of Price')
plt.xlabel('Price')
plt.show()

"""**Remove Outliers from Price Using Winsorization Method**

Nightly prices exhibited a highly

right-skewed distribution with extreme values. Capped the top 1% of the most expensive prices in the dataset Rather than removing high-priced listings, which may represent legitimate luxury properties, prices were winsorised at the upper percentile and log-transformed. This approach preserved all observations while reducing the influence of extreme values and improving model stability.
"""

# Compute 99th percentile cap
upper_cap = dublin_merged_df['price'].quantile(0.99)
print(f"99th percentile cap: {upper_cap}")

# Winsorise (cap extreme values)
dublin_merged_df['price'] = dublin_merged_df['price'].clip(upper=upper_cap)

# Log-transform for modelling
# dublin_merged_df['log_price'] = np.log1p(dublin_merged_df['price'])

# Check new distribution
# print(dublin_merged_df['price_capped'].describe())
# print(dublin_merged_df['log_price'].describe())

plt.figure(figsize=(8, 4))
plt.boxplot(dublin_merged_df['price'], vert=False)
plt.title('Boxplot of Price')
plt.xlabel('Price')
plt.show()

dublin_merged_df['price'].describe()

plt.figure(figsize=(15,5))
dublin_merged_df.set_index('host_since').resample('MS').size().plot(label='Hosts joining Airbnb', color='orange')
dublin_merged_df.set_index('first_review').resample('MS').size().plot(label='Listings getting their first review', color='red')
plt.title('Dublin hosts joining Airbnb and listings getting their first review in each month')
plt.legend()
plt.xlim('2009-11-25', '2025-04-30') # Limiting to whole months
plt.xlabel('')
plt.ylabel('')
plt.show()

# Creating dataframes for time series analysis
ts_host_since = pd.DataFrame(dublin_merged_df.set_index('host_since').resample('MS').size())
ts_first_review = pd.DataFrame(dublin_merged_df.set_index('first_review').resample('MS').size())

# Renaming columns
ts_host_since = ts_host_since.rename(columns={0: 'hosts'})
ts_host_since.index.rename('month', inplace=True)
ts_first_review = ts_first_review.rename(columns={0: 'reviews'})
ts_first_review.index.rename('month', inplace=True)

from statsmodels.tsa.seasonal import seasonal_decompose
def decompose_time_series(dublin_merged_df, title=''):
    """
    Plots the original time series and its decomposition into trend, seasonal and residual.
    """
    # Decomposing the time series
    decomposition = seasonal_decompose(dublin_merged_df)

    # Getting the trend, seasonality and noise
    trend = decomposition.trend
    seasonal = decomposition.seasonal
    residual = decomposition.resid

    # Plotting the original time series and the decomposition
    plt.figure(figsize=(12,8))
    plt.suptitle(title, fontsize=14, y=1)
    plt.subplots_adjust(top=0.80)
    plt.subplot(411)
    plt.plot(dublin_merged_df, label='Original')
    plt.legend(loc='upper left')
    plt.subplot(412)
    plt.plot(trend, label='Trend')
    plt.legend(loc='upper left')
    plt.subplot(413)
    plt.plot(seasonal,label='Seasonality')
    plt.legend(loc='upper left')
    plt.subplot(414)
    plt.plot(residual, label='Residuals')
    plt.legend(loc='upper left')
    plt.tight_layout()

decompose_time_series(ts_host_since, title='Number of hosts joining Airbnb each month')

decompose_time_series(ts_first_review, title='Number of Airbnb listings getting their first review each month')

plt.figure(figsize=(10,6))
plt.pie(dublin_merged_df.host_response_time.value_counts(), autopct='%1.1f%%')
plt.title('Distribution of Host Response Time')
plt.legend(labels = dublin_merged_df.host_response_time.value_counts().index, title="Time", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1))
plt.show()

# Create the barplot
plt.figure(figsize=(8,6))

x = dublin_merged_df.host_is_superhost.value_counts().index
y = dublin_merged_df.host_is_superhost.value_counts().values

sns.barplot(x=x, y=y, palette='viridis')

# Add values on top of the bars
for i in range(len(x)):
    plt.text(i, y[i] + 50, str(y[i]), ha='center', va='bottom')

# Add title and labels
plt.title('Superhost Distribution')
plt.ylabel('Count')
plt.xlabel('Is Superhost')

# Display the plot
plt.show()

plt.pie(dublin_merged_df.host_identity_verified.value_counts(), autopct='%1.1f%%')
plt.title('Host ID Verification')
plt.legend(labels = dublin_merged_df.host_identity_verified.value_counts().index, title="Time", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1))
plt.show()

plt.figure(figsize=(12,6))
sns.barplot(x=dublin_merged_df.neighbourhood_cleansed.value_counts().values[:10], y=dublin_merged_df.neighbourhood_cleansed.value_counts().index[:10], palette="gist_earth")
plt.title('Distribution of Neighbourhood Listings')
plt.ylabel('Borough')
plt.xlabel('Count')
plt.show()

'''
# use MarkerCluster
import folium
from folium.plugins import MarkerCluster

# Create map
map_center = [-6.266155, 53.350140]
m = folium.Map(location=map_center, zoom_start=12)

# Create a marker cluster layer
marker_cluster = MarkerCluster().add_to(m)

# Add points to the cluster layer
for idx, row in dublin_merged_df.iterrows():
    folium.Marker(
        [row['latitude'], row['longitude']],
        popup=row['name']
    ).add_to(marker_cluster)

# Display map
'''

'''
from folium.plugins import HeatMap

# Create list of points
points = dublin_merged_df[['latitude', 'longitude']].values.tolist()

# Add heatmap layer
HeatMap(points).add_to(m)
display(m)
'''

# Save the map
# m.save('my_heatmap.html')

"""Room Type Distribution"""

plt.figure(figsize=(12,6))
sns.barplot(x=dublin_merged_df.room_type.value_counts().values[:10], y=dublin_merged_df.room_type.value_counts().index[:10], palette="CMRmap")
plt.title('Distribution of Rooms type')
plt.ylabel('Rooms')
plt.xlabel('Count')
plt.show()

"""Bookable Distribution"""

# Create the barplot
plt.figure(figsize=(8,6))

x = dublin_merged_df.instant_bookable.value_counts().index
y = dublin_merged_df.instant_bookable.value_counts().values

sns.barplot(x=x, y=y, palette='prism_r')

# Add values on top of the bars
for i in range(len(x)):
    plt.text(i, y[i] + 50, str(y[i]), ha='center', va='bottom')

# Add title and labels
plt.title('Bookable Distribution')
plt.ylabel('Count')
plt.xlabel('Instant Bookable')

# Display the plot
plt.show()

"""Price Distribution after addressing outlier"""

# mean of the 'price' column
mean_value = dublin_merged_df['price'].mean()

# histogram
sns.histplot(dublin_merged_df['price'], kde=True)

# Add a vertical line at the mean
plt.axvline(mean_value, color='red', linestyle='dashed', linewidth=1, label=f'Mean: {mean_value:.2f}')

# Add legend and labels
plt.legend()
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Distribution of Price')

plt.show();

"""**Feature Engineering**

Sentiment Analysis (VADER)
Five basic preprocessing methods was carried out on the guest reviews (comment) these steps were carried so that model evaluation can produce correct and inadequate performance, increase the data quality and remove noise.
"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Ensure resources are available
nltk.download('vader_lexicon')
nltk.download('stopwords')

# 1. Case Folding
dublin_merged_df['comments'] = dublin_merged_df['comments'].astype(str).str.lower()

# 2. Remove Noise (Numbers and text in square brackets)
def remove_noise(text):
    text = re.sub(r'\[.*?\]', '', text) # Remove text in brackets
    text = re.sub(r'\d+', '', text)     # Remove numbers
    return text

dublin_merged_df['comments'] = dublin_merged_df['comments'].apply(remove_noise)

# 3. Non-ASCII Removal (Filtering for English-only characters)
def remove_non_ascii(text):
    return text.encode("ascii", "ignore").decode()

dublin_merged_df['comments'] = dublin_merged_df['comments'].apply(remove_non_ascii)

# 4. Normalization (Slang to Formal)
# Here is a representative sample mapping:
slang_dict = {"u": "you", "r": "are", "brb": "be right back", "thx": "thanks", "plz": "please"}
def normalize_slang(text):
    words = text.split()
    return " ".join([slang_dict.get(w, w) for w in words])

dublin_merged_df['comments'] = dublin_merged_df['comments'].apply(normalize_slang)

# 5. Stopword Removal (Including your specified noise words)
stop_words = set(stopwords.words('english'))
# Adding specific noise mentioned in your methodology
custom_noise = {"jeudidi", "ghh", "owo"}
stop_words.update(custom_noise)

def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in stop_words])

dublin_merged_df['comments'] = dublin_merged_df['comments'].apply(remove_stopwords)

# Final reduction check
dublin_merged_df = dublin_merged_df[dublin_merged_df['comments'].str.strip() != ""]

"""Sentiment score (compound score) the VADER sentiment analysis tool was used to capture the emotional tone of the guest reviews. Then for each guest review, a compound sentiment score was computed using VADER’s polarity_scores() method, which is a weighted composite that ranges from -1 (extremely negative) to +1 (extremely positive), such that Compound scores ≥ 0.05 are Positive, Compound scores > -0.05 and < 0.05 are Neutral and then Compound scores ≤ -0.05 Negative.


"""

# initialize vader Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# feature engineer and introduce a new column sentiment score
dublin_merged_df['compound_scores'] = dublin_merged_df['comments'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
dublin_merged_df.head(2)

"""Sentiment Score Distribution"""

# check the distribution of sentiment scores
plt.figure(figsize=(10, 6))
sns.histplot(dublin_merged_df['compound_scores'], kde=True)
plt.title('Distribution of Sentiment Scores')
plt.xlabel('Sentiment Score')
plt.ylabel('Frequency')
plt.show()

"""Sentiment Distribution in Pia chart"""

import pandas as pd
import matplotlib.pyplot as plt

sentiment_bins = [-1, -0.05, 0.05, 1]
sentiment_labels = ['Negative', 'Neutral', 'Positive']

dublin_merged_df['sentiment_category'] = pd.cut(
    dublin_merged_df['compound_scores'],
    bins=sentiment_bins,
    labels=sentiment_labels
)

sentiment_counts = dublin_merged_df['sentiment_category'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(
    sentiment_counts,
    labels=sentiment_counts.index,
    autopct='%1.1f%%',
    startangle=140
)
plt.title('Sentiment Distribution')
plt.axis('equal')  # makes the pie circular
plt.show()

"""Average Price Per Month Distribution"""

# month
dublin_merged_df['month'] = dublin_merged_df['date'].dt.month

# Calculate average price per month
avg_price_per_month = dublin_merged_df.groupby('month')['price'].mean().reset_index()

# Create a line plot
plt.figure(figsize=(10,6))
sns.lineplot(x='month', y='price', data=avg_price_per_month, marker='o')

# labels and title
plt.title('Average Price by Month')
plt.xlabel('Month')
plt.ylabel('Average Price (GBP)')
plt.xticks(ticks=range(1, 13), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
# Show the plot
plt.show();

"""Season Feature"""

# Ensuring date column is in datetime format
dublin_merged_df['date'] = pd.to_datetime(dublin_merged_df['date'])

# function to categorize seasons
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:  # 9, 10, 11
        return 'Autumn'

# Apply the function to create a 'season' column
dublin_merged_df['season'] = dublin_merged_df['date'].dt.month.apply(get_season)

# Ensure 'season' is a category with proper order
season_order = ['Winter', 'Spring', 'Summer', 'Autumn']
dublin_merged_df['season'] = pd.Categorical(dublin_merged_df['season'], categories=season_order, ordered=True)

# Calculate average price per season
avg_price_per_season = (
    dublin_merged_df
    .groupby('season')['price']
    .mean()
    .reset_index()
    .sort_values(by='price')
)

# Plotting
plt.figure(figsize=(10, 6))
ax = sns.barplot(x='season', y='price', data=avg_price_per_season, palette='Spectral')

# Add labels on top of bars
for bar in ax.patches:
    height = bar.get_height()
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        height + 5,
        f"£{height:.2f}",
        ha='center',
        va='bottom',
        color='black'
    )

# Add labels and title
ax.set_title('Average Price by Season')
ax.set_xlabel('Season')
ax.set_ylabel('Average Price (GBP)')

plt.tight_layout()
plt.show()

dublin_merged_df['season'].value_counts()

dublin_merged_df = pd.get_dummies(dublin_merged_df, columns=['season'], drop_first=True)

dublin_merged_df[['season_Spring', 'season_Summer', 'season_Autumn']].head()

bool_columns = ['season_Spring', 'season_Summer', 'season_Autumn']
dublin_merged_df[bool_columns] = dublin_merged_df[bool_columns].astype(int)

"""**Distance to City Centers**

A spatial feature measuring distance to Dublin city centre was engineered to capture the effect of geographical proximity on accommodation price
"""

from geopy.distance import geodesic

city_center = (53.3498, -6.2603)  # Dublin
dublin_merged_df['distance_to_center'] = dublin_merged_df.apply(
    lambda x: geodesic((x['latitude'], x['longitude']), city_center).km,
    axis=1
)

dublin_merged_df['distance_to_center'].head()

"""The scattered plot illustrates the relationship between accommodation price and distance from Dublin city centre. A clear downward trend is observed, indicating that listings closer to the city centre command higher prices, while those located further away tend to be cheaper. High-price outliers are concentrated near the city centre, suggesting that proximity to central business districts and tourist attractions allows hosts to charge premium rates. This empirical pattern supports the inclusion of a distance-to-centre feature in the predictive model"""

import seaborn as sns

sns.regplot(x='distance_to_center', y='price', data=dublin_merged_df,
            scatter_kws={'alpha':0.3})
plt.xlabel("Distance to City Centre (km)")
plt.ylabel("Price")
plt.title("Price vs Distance to City Centre")
plt.show()

corr = dublin_merged_df["distance_to_center"].corr(dublin_merged_df["compound_scores"])
print(f"Correlation between distance and sentiment: {corr:.3f}")

"""**Feature Encoding**

Feature encoding is performed because the  machine learning algorithms used in this project can only process numerical inputs.

Binary host attributes (superhost status, instant booking availability, profile picture presence, and identity verification) were encoded as 0/1 indicator variables. Missing values were treated as the absence of the attribute, reflecting platform logic and ensuring consistent interpretation across listings.
"""

dublin_merged_df[['host_is_superhost', 'instant_bookable', 'host_has_profile_pic', 'host_identity_verified']].head()

# Binary host/listing features
binary_cols = [
    'host_is_superhost',
    'instant_bookable',
    'host_has_profile_pic',
    'host_identity_verified'
]

for col in binary_cols:
    dublin_merged_df[col] = dublin_merged_df[col].astype(str).str.lower()
    dublin_merged_df[col] = dublin_merged_df[col].map({
        't': 1, 'true': 1, '1': 1,
        'f': 0, 'false': 0, '0': 0
    })
    dublin_merged_df[col] = dublin_merged_df[col].fillna(0).astype(int)

# Fill missing first
dublin_merged_df['host_response_time'] = dublin_merged_df['host_response_time'].fillna('unknown')

# Clean text: strip spaces and lowercase
dublin_merged_df['host_response_time'] = dublin_merged_df['host_response_time'].astype(str).str.strip().str.lower()

# Ordinal mapping
response_map = {
    'within an hour': 4,
    'within a few hours': 3,
    'within a day': 2,
    'a few days or more': 1,
    'unknown': 0
}

# Map values; unmapped categories become 0
dublin_merged_df['host_response_time'] = dublin_merged_df['host_response_time'].map(response_map).fillna(0).astype(int)

# Check
dublin_merged_df['host_response_time'].value_counts()

# Check result
#print(dublin_merged_df[binary_cols + ['host_response_time']].head())

print("Unique neighbourhoods:", dublin_merged_df['neighbourhood_cleansed'].nunique())
print("Unique room types:", dublin_merged_df['room_type'].nunique())

ohe_cols = ["neighbourhood_cleansed", "room_type"]

dublin_merged_df = pd.get_dummies(
    dublin_merged_df,
    columns=ohe_cols,
    drop_first=False,
    dtype=int
)

dublin_merged_df.info()

dublin_merged_df.columns

"""**Data Aggregation**

Data were grouped by listing ID to create one record per property. Fixed attributes (e.g. bedrooms, room type and neighbourhood indicators) were retained using the first observed value, while time-varying variables (e.g. price, review scores and sentiment measures) were averaged to obtain representative property-level values.
"""

dublin_aggregated_df = (
    dublin_merged_df
    .groupby('id_x')
    .agg({
    'price': 'first',
    'host_response_time': 'first',
    'host_response_rate': 'first',
    'host_acceptance_rate': 'first',
    'host_is_superhost': 'first',
    'host_listings_count': 'first',
    'host_has_profile_pic': 'first',
    'host_identity_verified': 'first',
    'latitude': 'first',
    'longitude': 'first',
    'accommodates': 'first',
    'bathrooms': 'first',
    'bedrooms': 'first',
    'beds': 'first',
    'minimum_nights': 'first',
    'maximum_nights': 'first',
    'availability_30': 'first',
    'availability_60': 'first',
    'availability_90': 'first',
    'availability_365': 'first',
    'availability_eoy': 'first',
    'number_of_reviews': 'first',
    'number_of_reviews_l30d': 'first',
    'number_of_reviews_ly': 'first',
    'estimated_occupancy_l365d': 'first',
    'estimated_revenue_l365d': 'first',
    'review_scores_rating': 'first',
    'review_scores_accuracy': 'first',
    'review_scores_cleanliness': 'first',
    'review_scores_checkin': 'first',
    'review_scores_communication': 'first',
    'review_scores_location': 'first',
    'review_scores_value': 'first',
    'instant_bookable': 'first',
    'reviews_per_month': 'first',
    'distance_to_center': 'first',

    # Neighbourhood dummies
    'neighbourhood_cleansed_Dn Laoghaire-Rathdown': 'first',
    'neighbourhood_cleansed_Dublin City': 'first',
    'neighbourhood_cleansed_Fingal': 'first',
    'neighbourhood_cleansed_South Dublin': 'first',

    # Room type dummies
    'room_type_Entire home/apt': 'first',
    'room_type_Hotel room': 'first',
    'room_type_Private room': 'first',
    'room_type_Shared room': 'first',

    # Review-derived features
    'compound_scores': 'mean',
    'season_Spring': 'mean',
    'season_Summer': 'mean',
    'season_Autumn': 'mean'
    })
        .reset_index()
)

dublin_aggregated_df.info()

"""Price Distribution after Data Aggregate."""

# mean of the 'price' column
mean_value = dublin_aggregated_df['price'].mean()

# histogram
sns.histplot(dublin_aggregated_df['price'], kde=True)

# Add a vertical line at the mean
plt.axvline(mean_value, color='red', linestyle='dashed', linewidth=1, label=f'Mean: {mean_value:.2f}')

# Add legend and labels
plt.legend()
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Distribution of Price')

plt.show();

"""**New feature correlation**"""

# correlation heat map for numerical variable

# Filter the dataframe to select only numeric columns
numeric_df = dublin_aggregated_df.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numeric_df.corr()

# Plot the correlation matrix
plt.figure(figsize=(25, 15))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()



"""**Base Line Model**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.model_selection import LearningCurveDisplay

X = dublin_aggregated_df.drop(columns=['price'])
y = dublin_aggregated_df.loc[X.index, 'price']   # align with selected rows

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipe_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('lr', LinearRegression())
])

pipe_lr.fit(X_train, y_train)

y_pred = pipe_lr.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# Learning Curve
LearningCurveDisplay.from_estimator(
    pipe_lr, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Linear Regression Learning Curve")
plt.show()

"""Feature Selection Using LASSO Regression"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV
from sklearn.pipeline import Pipeline

# Target
y = dublin_aggregated_df['price']

# Drop non-predictive or leakage columns
drop_cols = [
    'price', 'listing_url', 'picture_url', 'description', 'availability_eoy', 'availability_30', 'availability_60',
    'availability_90', 'availability_365', 'reviewer_name', 'host_since', 'first_review', 'last_review', 'estimated_revenue_l365d',
    'date', 'amenities', 'listing_id', 'id_x', 'id_y', 'reviewer_id', 'latitude', 'longitude'
]

X = dublin_aggregated_df.drop(columns=drop_cols, errors='ignore')

# Keep only numeric columns (LASSO needs numeric)
X = X.select_dtypes(include=['int64', 'float64', 'bool'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('lasso', LassoCV(cv=5, random_state=42, n_jobs=-1))
])

pipeline.fit(X_train, y_train)

lasso = pipeline.named_steps['lasso']
coef = pd.Series(lasso.coef_, index=X.columns)

selected_features = coef[coef != 0].sort_values(key=abs, ascending=False)

selected_features

# Filter for coefficients that are exactly zero
dropped_features = coef[coef == 0].index.tolist()

print(f"Number of features dropped: {len(dropped_features)}")
print(dropped_features)

print(f"Total features: {X.shape[1]}")
print(f"Selected features: {selected_features.shape[0]}")
print("\nSelected features:\n")
print(selected_features)

X_selected = X[selected_features.index]

X_selected.columns

X_selected.info()

y_test

# Save the X_test dataframe to a CSV file
y_test.to_csv('price_test_data.csv', index=False)

print("File 'price_test_data.csv' has been saved successfully.")

X_selected.describe()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.model_selection import LearningCurveDisplay

X = X_selected
y = dublin_aggregated_df.loc[X.index, 'price']   # align with selected rows

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipe_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('lr', LinearRegression())
])

pipe_lr.fit(X_train, y_train)

y_pred = pipe_lr.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# Learning Curve
LearningCurveDisplay.from_estimator(
    pipe_lr, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Linear Regression Learning Curve")
plt.show()

sns.scatterplot(x=y_test, y=y_pred, alpha = 0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Price")
plt.show()

residuals = y_test - y_pred
residuals

sns.histplot(residuals, kde=True)
plt.title("Histogram of Residuals")
plt.xlabel("Residuals")
plt.ylabel("Frequency")
plt.show()

# Get coefficients from the trained model
coef = pipe_lr.named_steps['lr'].coef_

feature_importance = pd.Series(coef, index=X.columns)

# Sort by absolute importance
feature_importance = feature_importance.sort_values(key=np.abs, ascending=False)

feature_importance

plt.figure(figsize=(15,10))
feature_importance.plot(kind='barh')
plt.gca().invert_yaxis()
plt.title("Feature Importance (Linear Regression Coefficients)")
plt.xlabel("Coefficient Value")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

# Decision Tree Model
dt_model = DecisionTreeRegressor(max_depth = 5, random_state = 42)

# Train
dt_model.fit(X_train, y_train)

# Predict Price
y_pred = dt_model.predict(X_test)

# Evaluation
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R²: {r2:.3f}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# Learning Curve
LearningCurveDisplay.from_estimator(
    dt_model, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Decision Tree Learning Curve")
plt.show()

# Random Forest Model
rf_model = RandomForestRegressor(max_depth = 5, random_state = 42)

# Train
rf_model.fit(X_train, y_train)

# Predict Price
y_pred = rf_model.predict(X_test)

# Evaluation
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R²: {r2:.3f}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# Learning Curve
LearningCurveDisplay.from_estimator(
    rf_model, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Random Forest Learning Curve")
plt.show()

from xgboost import XGBRegressor
xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# Learning Curve
LearningCurveDisplay.from_estimator(
    xgb, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("XGBoost Learning Curve")
plt.show()

sns.scatterplot(x=y_test, y=y_pred, alpha = 0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Price")
plt.show()

residuals = y_test - y_pred
residuals

sns.histplot(residuals, kde=True)
plt.title("Histogram of Residuals")
plt.xlabel("Residuals")
plt.ylabel("Frequency")
plt.show()

feature_names = X_train.columns

importance = xgb.feature_importances_

fi = pd.DataFrame({
    'feature': feature_names,
    'importance': importance
}).sort_values(by='importance', ascending=False)

fi

import matplotlib.pyplot as plt

plt.figure(figsize=(15,10))
plt.barh(fi["feature"], fi["importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("XGBoost Feature Importance")
plt.gca().invert_yaxis()
plt.show()

y_test

"""**Log Price**"""

y = dublin_aggregated_df.loc[X_selected.index, 'price']

y_log = np.log1p(y)   # log(1 + price) → safe if any zero values

X = X_selected

X_train, X_test, y_train, y_test = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

pipe_lr_log = Pipeline([
    ('scaler', StandardScaler()),
    ('lr', LinearRegression())
])

pipe_lr_log.fit(X_train, y_train)

y_pred_log = pipe_lr_log.predict(X_test)

print("R2 (log):", r2_score(y_test, y_pred_log))
print("MAE (log):", mean_absolute_error(y_test, y_pred_log))
print("RMSE (log):", np.sqrt(mean_squared_error(y_test, y_pred_log)))

# Learning Curve
LearningCurveDisplay.from_estimator(
    pipe_lr_log, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Linear regression Learning Curve")
plt.show()

sns.scatterplot(x=y_test, y=y_pred_log, alpha = 0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Price")
plt.show()

y_pred_price = np.expm1(y_pred_log)
y_true_price = np.expm1(y_test)

print("MAE (€):", mean_absolute_error(y_true_price, y_pred_price))
print("RMSE (€):", np.sqrt(mean_squared_error(y_true_price, y_pred_price)))

residuals = y_test - y_pred_log
residuals

sns.histplot(residuals, kde=True)
plt.title("Histogram of Residuals")
plt.xlabel("Residuals")
plt.ylabel("Frequency")
plt.show()

# Get coefficients from the trained model
coef = pipe_lr_log.named_steps['lr'].coef_

feature_importance = pd.Series(coef, index=X.columns)

# Sort by absolute importance
feature_importance = feature_importance.sort_values(key=np.abs, ascending=False)

feature_importance

plt.figure(figsize=(15,10))
feature_importance.plot(kind='barh')
plt.gca().invert_yaxis()
plt.title("Feature Importance (Linear Regression Coefficients)")
plt.xlabel("Coefficient Value")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

# Decision Tree Model
dt_model_log = DecisionTreeRegressor(max_depth = 5, random_state = 42)

# Train
dt_model_log.fit(X_train, y_train)

# Predict Price
y_pred_log = dt_model.predict(X_test)

# Evaluation
r2 = r2_score(y_test, y_pred_log)
mae = mean_absolute_error(y_test, y_pred_log)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_log))

print(f"R²: {r2:.3f}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# Learning Curve
LearningCurveDisplay.from_estimator(
    dt_model_log, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Decision Tree Learning Curve")
plt.show()

y_pred_price = np.expm1(y_pred_log)
y_true_price = np.expm1(y_test)

print("MAE (€):", mean_absolute_error(y_true_price, y_pred_price))
print("RMSE (€):", np.sqrt(mean_squared_error(y_true_price, y_pred_price)))

# Random Forest Model
rf_model_log = RandomForestRegressor(max_depth = 5, random_state = 42)

# Train
rf_model_log.fit(X_train, y_train)

# Predict Price
y_pred_log = rf_model_log.predict(X_test)

# Evaluation
r2 = r2_score(y_test, y_pred_log)
mae = mean_absolute_error(y_test, y_pred_log)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_log))

print(f"R²: {r2:.3f}")
print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

# Learning Curve
LearningCurveDisplay.from_estimator(
    rf_model_log, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("Random Forest Learning Curve")
plt.show()

y_pred_price = np.expm1(y_pred_log)
y_true_price = np.expm1(y_test)

print("MAE (€):", mean_absolute_error(y_true_price, y_pred_price))
print("RMSE (€):", np.sqrt(mean_squared_error(y_true_price, y_pred_price)))

xgb_log = XGBRegressor(
    n_estimators=400,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_log.fit(X_train, y_train)

y_pred_log = xgb_log.predict(X_test)


r2 = r2_score(y_test, y_pred_log)
mae = mean_absolute_error(y_test, y_pred_log)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_log))

print(f"R²: {r2:.3f}")
print(f"MAE: {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

# Learning Curve
LearningCurveDisplay.from_estimator(
    xgb_log, X, y,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=5,
    scoring='neg_mean_squared_error'
)
plt.title("XGBoost Learning Curve")
plt.show()

y_pred_price = np.expm1(y_pred_log)
y_true_price = np.expm1(y_test)

print("MAE (€):", mean_absolute_error(y_true_price, y_pred_price))
print("RMSE (€):", np.sqrt(mean_squared_error(y_true_price, y_pred_price)))

""""The XGBoost learning curve demonstrates healthy convergence. The steady improvement in the test score as we increase data volume, combined with the lack of a massive gap between training and testing performance, proves that the model is well-generalized. This confirms that the features we selected—including the sentiment scores—are providing consistent predictive power rather than causing the model to overfit to specific training examples."
"""

import joblib

# Save the model
joblib.dump(xgb_log, "xgb_log_model.pkl")

# How to load it back later
loaded_xgb = joblib.load("xgb_log_model.pkl")

from sklearn.model_selection import learning_curve
import matplotlib.pyplot as plt

def learn_curves(pipe, X, y, cv=5):
    """
    Generates learning curves in log-scale MSE
    """
    train_sizes, train_scores, val_scores = learning_curve(
        pipe, X, y, cv=cv, scoring='neg_mean_squared_error', train_sizes=np.linspace(0.1, 1.0, 10)
    )

    train_scores_mean = -np.mean(train_scores, axis=1)
    val_scores_mean = -np.mean(val_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.plot(train_sizes, train_scores_mean, 'o-', label='Training Error')
    plt.plot(train_sizes, val_scores_mean, 'o-', label='Validation Error')
    plt.xlabel('Training Set Size')
    plt.ylabel('Mean Squared Error (log-scale)')
    plt.title('Learning Curves')
    plt.legend()
    plt.grid(True)
    plt.show()

# Plot learning curves
learn_curves(xgb_log, X, y)

sns.scatterplot(x=y_test, y=y_pred_log, alpha = 0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Price")
plt.show()

residuals = y_test - y_pred_log
residuals

sns.histplot(residuals, kde=True)
plt.title("Histogram of Residuals")
plt.xlabel("Residuals")
plt.ylabel("Frequency")
plt.show()

residuals = y_test - y_pred_log
residuals

import matplotlib.pyplot as plt

# 1. Slice the DataFrame to the top 20
fi_top20 = fi.head(20)

# 2. Plot using the sliced data
plt.figure(figsize=(15, 10))
plt.barh(fi_top20["feature"], fi_top20["importance"], color='skyblue')
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 20 XGBoost Feature Importance")

# Invert y-axis so the highest importance is at the top
plt.gca().invert_yaxis()
plt.show()

import numpy as np
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def cross_validate_results(model, X_train, y_train, cv=5):
    """
    Performs cross-validation on training data and prints metrics.
    """
    # cross_val_predict generates 'out-of-fold' predictions
    y_pred_cv = cross_val_predict(model, X_train, y_train, cv=cv)

    # Calculate metrics
    # Note: root_mean_squared_error(y_true, y_pred) is available in sklearn 1.4+
    # For older versions, we use np.sqrt(mean_squared_error)
    rmse = np.sqrt(mean_squared_error(y_train, y_pred_cv))
    mae = mean_absolute_error(y_train, y_pred_cv)
    r2 = r2_score(y_train, y_pred_cv)

    print(f"--- {cv}-Fold Cross-Validation Results ---")
    print(f"RMSE: {rmse:.4f}")
    print(f"MAE:  {mae:.4f}")
    print(f"R²:   {r2:.4f}")
    print("-" * 10)

# Correct usage: Use your TRAINING data here
cross_validate_results(xgb_log, X_train, y_train, cv=5)

import numpy as np
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# 1. Define the parameter space
# We focus on depth and learning rate to control complexity
param_distributions = {
    'n_estimators': [400, 600, 800],
    'max_depth': [3, 4, 5, 6],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9],
    'reg_alpha': [0, 0.1, 1],    # L1 regularization
    'reg_lambda': [1, 2, 5],     # L2 regularization
    'gamma': [0, 0.1, 0.2]       # Minimum loss reduction to split
}

# 2. Initialize the model
xgb_reg = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)

# 3. Setup the Randomized Search
# n_iter=20 will try 20 different random combinations
random_search = RandomizedSearchCV(
    estimator=xgb_reg,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='r2',
    cv=5,
    verbose=1,
    n_jobs=-1,
    random_state=42
)

# 4. Fit the search (Ensure you use your log-transformed y_train)
random_search.fit(X_train, y_train)

# 5. Extract the best model
best_xgb = random_search.best_estimator_

# 6. Evaluate
y_pred_log = best_xgb.predict(X_test)

print("--- Tuned XGBoost Results ---")
print("Best Params:", random_search.best_params_)
print("R2 (log):", r2_score(y_test, y_pred_log))
print("MAE (log):", mean_absolute_error(y_test, y_pred_log))
print("RMSE (log):", np.sqrt(mean_squared_error(y_test, y_pred_log)))

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Get predictions (on the log scale)
y_pred_log = best_xgb.predict(X_test)

# 2. Calculate Residuals
# Residual = Actual - Predicted
residuals = y_test - y_pred_log

# 3. Create the Residual Plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_pred_log, y=residuals, alpha=0.5)
plt.axhline(y=0, color='r', linestyle='--')
plt.title('XGBoost Residual Plot (Log Scale)')
plt.xlabel('Predicted Log Price')
plt.ylabel('Residuals')
plt.show()





'''
sns.pairplot(
    selected_features,
    kind="reg",
    plot_kws={"line_kws": {"color": "red"}, "scatter_kws": {"alpha": 0.4}}
)
plt.suptitle('Pairplot with Regression Lines', y=1.02)
plt.show()
'''

"""**Select best predictors**

**Modelling**

Multiple linear regression model was set as the baseline model in order to see how well the model performs with other complex model and it is also used for interpretation.

The preferred model was selected based on:

(a) Highest mean R², lowest MAE and RMSE;

(b) Interpretability of feature effects

the remaining unexplained variation in the price to data that is not present, such as picture quality e.tc.

**XGBoost Hyper Parameter tuning**

Hyperparameter tuning was performed using RandomizedSearchCV, which randomly samples parameter combinations from a predefined search space, providing a more computationally efficient alternative to grid search while achieving comparable optimisation performance (Bergstra and Bengio, 2012). The parameters tuned included n_estimators, max_depth, and learning_rate, which influence model complexity and learning dynamics.

Three-fold cross-validation was applied to reduce variance in performance estimates and improve generalisability. Model performance was evaluated using the root mean squared error (RMSE), which penalises large errors and is appropriate for regression tasks (Hastie, Tibshirani and Friedman, 2009). The optimal model configuration was selected and used for subsequent analysis.
"""

dublin_merged_df.to_csv("dublin_merged_df.csv", index=False)

dublin_aggregated_df.to_csv("dublin_aggregated_df.csv", index=False)

dublin_merged_df.info()

dublin_merged_df.to_csv("dublin_merged_df.csv.gz", index=False, compression="gzip")

#recommender_df = dublin_merged_df[['reviewer_id','id_x','description','compound_scores','price']]
#recommender_df.to_csv("recommender_data.csv.gz", index=False, compression="gzip")



# check the distribution of sentiment scores
plt.figure(figsize=(8, 5))
sns.histplot(dublin_merged_df['compound_scores'], bins=100, kde=True)
plt.title('Distribution of Sentiment Scores')
plt.xlabel('Sentiment Score')
plt.ylabel('Frequency')
plt.show()

'''
# Clip the Negative Outliers ---
# Since my data is mostly 0.75 to 1.0, a -1.0 is an extreme outlier.
# I will "clip" the bottom at -0.5.
# This keeps the 'bad' signal but reduces its mathematical weight.
dublin_merged_df['compound_scores'] = dublin_merged_df['compound_scores'].clip(lower=-0.5, upper=1.0)
'''

"""**Prepare the data (User–Item–Rating matrix)**"""

from surprise import Reader, SVD, Dataset, accuracy, BaselineOnly, SlopeOne
from surprise.model_selection import GridSearchCV, train_test_split, cross_validate
from surprise.model_selection import train_test_split

# Keep only required columns
ratings_df = dublin_merged_df[
    ['reviewer_id', 'id_x', 'price', 'description', 'accommodates', 'beds', 'bedrooms', 'bathrooms', 'picture_url', 'listing_url', 'compound_scores']
].dropna()

"""**Define Surprise reader (VADER scale)**"""

reader = Reader(rating_scale=(-1, 1))
data = Dataset.load_from_df(
    ratings_df[['reviewer_id', 'id_x', 'compound_scores']],
    reader
)

ratings_df.head(1)

"""**Proper Surprise train/test split**"""

trainset, testset = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)

testset

ratings_df

# 1. Convert the list of tuples into a Pandas DataFrame
# The Surprise testset structure is typically (user_id, item_id, actual_rating)
df_test = pd.DataFrame(testset, columns=['user_id', 'item_id', 'actual_rating'])

# 2. Now you can save it to a CSV
df_test.to_csv('rec_test_data.csv', index=False)

print("File 'rec_test_data.csv' has been saved successfully.")

# Initialize and cross-validate BaselineOnly model
baseline_model = BaselineOnly()
cv_baseline = cross_validate(baseline_model, data, cv=5, verbose=True)

import joblib

# 1. Build the full trainset
full_trainset = data.build_full_trainset()

# 2. Fit the baseline model on the entire dataset
baseline_model = BaselineOnly()
baseline_model.fit(full_trainset)

# 3. Save using joblib with your requested filename
joblib.dump(baseline_model, 'baseline_model_joblib.pkl')

print("Model saved successfully as baseline_model_joblib.pkl")

slope_one = SlopeOne()
cv_slopeone = cross_validate(slope_one, data, cv=5, verbose=True)

"""**Create SVD Model Object**"""

svd_model = SVD()
cv_svd_model = cross_validate(svd_model, data, cv=5, verbose=True)

ratings_df.to_csv("rating_data.csv.gz", index=False, compression="gzip")

import joblib

# Note: cross_validate evaluates the model but doesn't leave svd_model 'trained' on a full dataset.
# Train on your full trainset before saving:
trainset = data.build_full_trainset()
svd_model.fit(trainset)

# Save the model
joblib.dump(svd_model, "svd_model_joblib.pkl")

# How to load it back later
loaded_svd = joblib.load("svd_model_joblib.pkl")





ratings_df.info()

import pandas as pd

# Define the bin edges
# We use -1.1 and 1.1 to ensure the exact values of -1.0 and 1.0 are included
bins = [-1.1, -0.5, 0.05, 0.5, 0.9, 1.1]

# Define the labels for each bin
labels = [
    '1 (Critical failure)',
    '2 (Disappointing)',
    '3 (Average/Polite)',
    '4 (Standard Good Stay)',
    '5 (Exceptionally Good)'
]

# Create the new column
ratings_df['rating_label'] = pd.cut(ratings_df['compound_scores'], bins=bins, labels=labels)

# If you want just the numeric rating (1-5) as an integer:
ratings_df['rating_score'] = pd.cut(ratings_df['compound_scores'], bins=bins, labels=[1, 2, 3, 4, 5]).astype(int)

# Check the distribution of your new ratings
print(ratings_df['rating_label'].value_counts().sort_index())

import pandas as pd
import numpy as np
from surprise import Dataset, Reader, SVD, SlopeOne, BaselineOnly
from surprise.model_selection import cross_validate

# 1. Setup the data
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(ratings_df[['reviewer_id', 'id_x', 'rating_score']], reader)

# 2. Define the models with verbose=False to stop the "Estimating biases" spam
models = [
    BaselineOnly(bsl_options={'method': 'als', 'n_epochs': 5}, verbose=False),
    SlopeOne(),
    SVD()
]

results = []

for model in models:
    print(f"Running {model.__class__.__name__}...")
    # Using 3-fold CV to save time on 275k rows
    cv_results = cross_validate(model, data, measures=['RMSE', 'MAE'], cv=3, verbose=False)

    # Use np.mean() instead of .mean() to avoid the AttributeError
    results.append({
        'Model': model.__class__.__name__,
        'RMSE': np.mean(cv_results['test_rmse']),
        'MAE': np.mean(cv_results['test_mae']),
        'Fit Time (s)': np.mean(cv_results['fit_time'])
    })

# 3. Display the comparison table
results_df = pd.DataFrame(results)
print("\n--- Model Comparison ---")
print(results_df.sort_values(by='RMSE'))

from surprise import BaselineOnly, Dataset, Reader

# 1. Prepare the model
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(ratings_df[['reviewer_id', 'id_x', 'rating_score']], reader)
full_trainset = data.build_full_trainset()

# 2. Train using ALS (Alternating Least Squares)
# We use ALS because it's robust for this kind of bias estimation
bsl_options = {'method': 'als', 'n_epochs': 5}
algo = BaselineOnly(bsl_options=bsl_options)
algo.fit(full_trainset)

# 3. Quick Prediction Function
def get_baseline_recommendations(user_id, n=5):
    all_ids = ratings_df['id_x'].unique()
    # Predict for all items
    predictions = [algo.predict(user_id, iid) for iid in all_ids]
    # Sort by the estimated rating
    predictions.sort(key=lambda x: x.est, reverse=True)

    top_n_ids = [p.iid for p in predictions[:n]]
    return ratings_df[ratings_df['id_x'].isin(top_n_ids)][['id_x', 'price', 'description']].drop_duplicates('id_x')

# Test it
user_to_check = ratings_df['reviewer_id'].iloc[0]
print(f"Baseline Recommendations for User {user_to_check}:")
print(get_baseline_recommendations(user_to_check))

algo = BaselineOnly()
algo.fit(trainset)  # This creates the 'trainset' attribute

# 3. Now you can predict
algo.predict(444004, 44077, verbose=True)

# check the distribution of sentiment scores
plt.figure(figsize=(8, 5))
sns.histplot(ratings_df['rating_score'], bins=50, kde=True)
plt.title('Distribution of Sentiment Scores')
plt.xlabel('Sentiment Score')
plt.ylabel('Frequency')
plt.show()

# Check the distribution of your new ratings
print(ratings_df['rating_score'].value_counts().sort_index())

ratings_df.info()

'''
from scipy.sparse import csr_matrix
ratings_df = pd.DataFrame(dublin_merged_df)

# 2. Define the Binning Logic
def map_vader_to_rating(score):
    if score >= 0.9:
        return 5  # Exceptional
    elif score >= 0.5:
        return 4  # Good
    elif score >= 0.05:
        return 3  # Positive/Ok
    elif score >= -0.5:
        return 2  # Disappointing / Neutral spike
    else:
        return 1  # Very Bad

# 3. Apply the mapping
ratings_df['derived_rating'] = ratings_df['compound_scores'].apply(map_vader_to_rating)

# 4. Create the Rating Matrix (Pivot Table)
# Note: We fill NaN with 0 because a 0 indicates "No Review"
rating_matrix_df = ratings_df.pivot_table(index='reviewer_id', columns='id_x', values='derived_rating').fillna(0)

# 5. Convert to Sparse Matrix for Memory Efficiency
# This is what most recommendation models (SVD, ALS) actually take as input
sparse_rating_matrix = csr_matrix(rating_matrix_df.values)

print("Mapped Dataframe:")
print(ratings_df[['compound_scores', 'derived_rating']])
print("\nSparse Matrix Shape:", sparse_rating_matrix.shape)
'''

'''
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(1, 5))
# Reshape is needed because the scaler expects a 2D array
ratings_df['rating_scale'] = scaler.fit_transform(ratings_df[['compound_scores']])
'''

reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(
    ratings_df[['reviewer_id', 'id_x', 'rating_score']],
    reader
)

trainset, testset = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)

# Initialize and cross-validate BaselineOnly model
baseline_model = BaselineOnly()
cv_baseline = cross_validate(baseline_model, data, cv=5, verbose=True)











from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

ratings_df['compound_scores_z'] = scaler.fit_transform(
    ratings_df[['compound_scores']]
)

from surprise import Dataset, Reader

reader = Reader(
    rating_scale=(
        ratings_df['compound_scores_z'].min(),
        ratings_df['compound_scores_z'].max()
    )
)

data = Dataset.load_from_df(
    ratings_df[['reviewer_id', 'id_x', 'compound_scores_z']],
    reader
)

from surprise.model_selection import train_test_split

trainset, testset = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)

# Initialize and cross-validate BaselineOnly model
baseline_model = BaselineOnly()
cv_baseline = cross_validate(baseline_model, data, cv=5, verbose=True)

slope_one = SlopeOne()
cv_slopeone = cross_validate(slope_one, data, cv=5, verbose=True)

svd_model = SVD()
cv_svd_model = cross_validate(svd_model, data, cv=5, verbose=True)













"""**Training Model**"""

svd_model.fit(trainset)

"""**Making Predictions and Calculating Errors**"""

predictions = svd_model.test(testset)

accuracy.rmse(predictions)

svd_model.predict(393348, 44077, verbose=True)

svd_model.predict(444004, 44077, verbose=True)

ratings_df[ratings_df["reviewer_id"] == 393348]

"""**Hyperparameter tuning**"""

from surprise import SVD
from surprise.model_selection import GridSearchCV

param_grid = {
    'n_factors': [20, 50, 100],
    'n_epochs': [10, 20],
    'reg_all': [0.02, 0.05, 0.1],
    'lr_all': [0.002, 0.005]
}

gs = GridSearchCV(
    SVD,
    param_grid,
    measures=['rmse'],
    cv=5,
    n_jobs=-1
)

gs.fit(data)

best_svd = gs.best_estimator['rmse']
trainset = data.build_full_trainset()
best_svd.fit(trainset)

best_svd.predict(393348, 44077, verbose=True)

print("Best RMSE:", gs.best_score['rmse'])
print("Best params:", gs.best_params['rmse'])

# Example: predictions from test set
predictions = best_svd.test(testset)

# Convert predictions to a DataFrame
pred_df = pd.DataFrame([{
    'user': pred.uid,
    'item': pred.iid,
    'true_rating': pred.r_ui,
    'pred_rating': pred.est
} for pred in predictions])

plt.figure(figsize=(10,5))
sns.histplot(pred_df['pred_rating'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Predicted Sentiment Scores')
plt.xlabel('Predicted Sentiment (-1 to 1)')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10,5))
sns.kdeplot(pred_df['true_rating'], label='Actual', color='green', fill=True, alpha=0.3)
sns.kdeplot(pred_df['pred_rating'], label='Predicted', color='blue', fill=True, alpha=0.3)
plt.title('Actual vs Predicted Sentiment Distribution')
plt.xlabel('Sentiment Score (-1 to 1)')
plt.ylabel('Density')
plt.legend()
plt.show()

'''
plt.figure(figsize=(12,6))
sns.boxplot(x='user', y='pred_rating', data=pred_df)
plt.xticks(rotation=90)
plt.title('Predicted Sentiment Distribution per User')
plt.show()
'''

dir(svd_model)

ratings_df.head()

"""**Applying Z-score**

Due to the highly right-skewed and zero-inflated distribution of VADER compound sentiment scores, Z-score standardization was applied prior to collaborative filtering. This transformation centred the data around zero and reduced the influence of extreme positive values, thereby improving numerical stability and model learning.

“Previous work on collaborative filtering has shown that normalization strategies such as Z-score standardization can improve similarity calculations and recommendation quality by rescaling features to zero mean and unit variance (Patoulia, 2023). Similarly, research integrating sentiment analysis with collaborative filtering demonstrates that sentiment scores extracted from text reviews can provide enhanced user preference signals when properly preprocessed (Dang et al., 2021; Gajula, 2025). Therefore, applying Z-score standardization to skewed VADER compound sentiment scores stabilizes their distribution and supports improved collaborative filtering performance in this study.”

Ref

Patoulia, A. A. (2023) A comparative study of collaborative filtering in product recommendation systems. Available at: [paper URL] (Accessed: DD Month YYYY).

Dang, C. N. et al. (2021) An approach to integrating sentiment analysis into recommender systems. Available at: [paper URL] (Accessed: DD Month YYYY).

Gajula, Y. (2025) Sentiment-aware recommendation systems in e-commerce: A review from an NLP perspective. Available at: [paper URL] (Accessed: DD Month YYYY).


"""

'''
# Handle the 0.0 Neutral Spike ---
# I convert 0.0 to NaN. Such that when i calculate Z-scores or Means,
# these "empty" reviews won't pull the average down.
ratings_df['compound_scores'] = ratings_df['compound_scores'].replace(0.0, np.nan)
'''

ratings_df['compound_scores'].head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

ratings_df['compound_scores_z'] = scaler.fit_transform(
    ratings_df[['compound_scores']]
)

# check the distribution of sentiment scores
plt.figure(figsize=(8, 5))
sns.histplot( ratings_df['compound_scores_z'], bins=500, kde=True)
plt.title('Distribution of Sentiment Scores')
plt.xlabel('Sentiment Score')
plt.ylabel('Frequency')
plt.show()

"""Build Surprise dataset using standardized scores"""

from surprise import Dataset, Reader

reader = Reader(
    rating_scale=(
        ratings_df['compound_scores_z'].min(),
        ratings_df['compound_scores_z'].max()
    )
)

data = Dataset.load_from_df(
    ratings_df[['reviewer_id', 'id_x', 'compound_scores_z']],
    reader
)

"""Train / test split"""

from surprise.model_selection import train_test_split

trainset, testset = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)

# Initialize and cross-validate BaselineOnly model
baseline_model = BaselineOnly()
cv_baseline = cross_validate(baseline_model, train_data, cv=5, verbose=True)



"""GridSearch"""

from surprise.model_selection import GridSearchCV
from surprise import SVD

param_grid = {
    'n_factors': [20, 50, 100],
    'n_epochs': [10, 20],
    'reg_all': [0.02, 0.05, 0.1],
    'lr_all': [0.002, 0.005]
}

gs = GridSearchCV(
    SVD,
    param_grid,
    measures=['rmse'],
    cv=5,
    n_jobs=-1
)

gs.fit(data)

best_svd = gs.best_estimator['rmse']

"""Fit tuned model on full data"""

full_trainset = data.build_full_trainset()
best_svd.fit(full_trainset)

"""Evaluate RMSE"""

predictions = best_svd.test(testset)

from surprise import accuracy
accuracy.rmse(predictions)

best_svd.predict(393348, 44077, verbose=True)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(ratings_df['compound_scores_z'], bins=30, kde=True, color='orange')
plt.title('Distribution of Z-score Standardized Compound Scores')
plt.xlabel('Z-score Standardized Sentiment')
plt.ylabel('Count')
plt.show()

import pandas as pd

# Convert predictions from SVD into a DataFrame
pred_df = pd.DataFrame([{
    'user': pred.uid,
    'item': pred.iid,
    'true_rating': pred.r_ui,
    'pred_rating': pred.est
} for pred in predictions])

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.scatterplot(x='true_rating', y='pred_rating', data=pred_df, alpha=0.5)
plt.plot([-3, 3], [-3, 3], color='red', linestyle='--')  # perfect prediction line
plt.title('Predicted vs Actual Z-score Standardized Sentiment')
plt.xlabel('True Standardized Sentiment')
plt.ylabel('Predicted Standardized Sentiment')
plt.xlim(-3, 3)
plt.ylim(-3, 3)
plt.show()

plt.figure(figsize=(10,5))
sns.kdeplot(pred_df['true_rating'], label='Actual', fill=True, alpha=0.3, color='green')
sns.kdeplot(pred_df['pred_rating'], label='Predicted', fill=True, alpha=0.3, color='blue')
plt.title('Distribution of Predicted vs Actual Z-score Standardized Sentiment')
plt.xlabel('Standardized Sentiment')
plt.ylabel('Density')
plt.legend()
plt.show()

pred_df['residual'] = pred_df['pred_rating'] - pred_df['true_rating']

plt.figure(figsize=(10,5))
sns.histplot(pred_df['residual'], bins=30, kde=True, color='orange')
plt.title('Distribution of Prediction Errors (Residuals)')
plt.xlabel('Predicted - True Z-score Sentiment')
plt.ylabel('Count')
plt.show()

"""**Train final SVD model**"""

best_params = gs.best_params['rmse']

final_model = SVD(
    **best_params,
    random_state=42
)

final_model.fit(trainset)

"""**Evaluate on unseen data**"""

from surprise import accuracy

predictions = final_model.test(testset)
accuracy.rmse(predictions)

dublin_merged_df

dublin_merged_df.columns

from IPython.display import display, HTML, Image

def recommend_airbnbs(user_id, listings_df=ratings_df):
    """
    Recommend 5 personalized Dublin Airbnb listings to the user based on sentiment scores.
    """

    # Get listings already rated by the user
    user_listings = listings_df[listings_df['reviewer_id'] == user_id]['id_x'].unique()

    # Get all listings
    all_listings = listings_df['id_x'].unique()

    # Identify listings not yet rated by the user
    listings_to_predict = list(set(all_listings) - set(user_listings))

    # Create matrix for predictions
    user_listing_pairs = [(user_id, listing_id, 0) for listing_id in listings_to_predict]

    # Predict ratings
    predictions = best_svd.test(user_listing_pairs)

    # Top 5 recommendations
    top_5_recs = sorted(predictions, key=lambda x: x.est, reverse=True)[:5]

    # Retrieve listing details
    top_5_listings = [listings_df[listings_df['id_x'] == rec.iid] for rec in top_5_recs]

    # Display recommendations
    for idx, listing in enumerate(top_5_listings):

        name = listing.description.iloc[0]
        url = listing.listing_url.iloc[0]

        listing_name_link = f'<a href="{url}" target="_blank">{name}</a>'

        print(f'Recommendation #{idx + 1}:')
        display(HTML(listing_name_link))

        # Optional image
        # display(Image(listing.picture_url.iloc[0], width=250))

        print('\n')

recommend_airbnbs(user_id=444004)

ratings_df.columns

"""**Strengths & limitations**

- Strengths

Avoids rating sparsity (text → signal)

Captures latent preferences

Scales well


- Limitations

Sentiment ≠ booking probability

No price/location constraints

Cold-start users/listings
"""

import joblib

# Save the trained model
# joblib.dump(final_model, 'svd_model_joblib.pkl')

# Load it later
# loaded_model = joblib.load('svd_model_joblib.pkl')

import joblib

# Save the pipeline
# joblib.dump(xgb_model, "xgb_price_model.pkl")

# Later, to load it
# loaded_xgb_model = joblib.load("xgb_price_model.pkl")

# Use it for prediction
# y_pred = loaded_xgb_model.predict(X_test)

'''
from surprise import SVD
from surprise.model_selection import GridSearchCV


# Parameter tuning for SVD model
params = {
    'n_factors': [20, 50, 100],
    'n_epochs': [5, 10],
    'reg_all': [0.02, 0.05, 0.1],
    'lr_all': [0.002, 0.005, 0.01]
}
gridsearch_svd = GridSearchCV(SVD, param_grid=params, cv=5, measures=['rmse'], n_jobs=-1)
gridsearch_svd.fit(train_data)
'''

'''
# Display best score and parameters
print("Best RMSE score from GridSearch:", gridsearch_svd.best_score["rmse"])
print("Best parameters for SVD model:", gridsearch_svd.best_params["rmse"])
'''

'''
final_model = SVD(n_factors=20,
                  n_epochs=10,
                  reg_all=0.1,
                  lr_all=0.01,
                  random_state=42)

final_model.fit(trainset)
'''



'''
import pandas as pd
from surprise import SVD, Dataset, Reader, accuracy
from surprise.model_selection import train_test_split

# 1. Aggregate: One score per user per item
rating_data = dublin_merged_df.groupby(['user_id', 'item_id'])['compound'].mean().reset_index()

# 2. Rescale: Moving from (-1 to 1) to (1 to 5) for better SVD performance
# This maps -1 -> 1, 0 -> 3, and 1 -> 5
rating_data['rating'] = 3 + (rating_data['compound'] * 2)

# 3. Define the Scale for the Reader
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(rating_data[['user_id', 'item_id'], 'rating']], reader)
'''

'''
# Split into training and testing sets
trainset, testset = train_test_split(data, test_size=0.2)

# Initialize the SVD algorithm
algo = SVD()

# Train the model
algo.fit(trainset)

# Predict a score for a specific user and item
# uid = user id, iid = item id
prediction = algo.predict(uid='User_123', iid='Guinness_Storehouse')
print(f"Predicted Sentiment Rating: {prediction.est:.2f}")
'''

from surprise import SVD, Dataset, Reader
import pandas as pd

# 1. Rescale your compound_scores to a 1-5 scale
df['rating'] = (df['compound_scores'] + 1) * 2 + 1

# 2. Define the Reader with your new scale
reader = Reader(rating_scale=(1, 5))

# 3. Load data (columns must be: user_id, item_id, rating)
data = Dataset.load_from_df(df[['reviewer_id', 'id_x', 'rating']], reader)

# 4. Train the SVD model
trainset = data.build_full_trainset()
algo = SVD()
algo.fit(trainset)

# 5. Predict for a specific user and listing
# uid = reviewer_id, iid = id_x
prediction = algo.predict(uid=393348, iid=44077)
print(f"Predicted rating: {prediction.est:.2f}")